# Build Gpay in a stock Go builder container
FROM golang:1.17-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git bash

ADD . /gpay
RUN cd /gpay && make gpay-all

CMD ["/bin/bash"]

# Pull Gpay into a second stage deploy alpine container
FROM alpine:latest

RUN apk add --no-cache ca-certificates
COPY --from=builder /gpay/build/bin/gpay /usr/local/bin/
COPY --from=builder /gpay/build/bin/bootnode /usr/local/bin/

EXPOSE 8545 8546 8547 30303 30303/udp
