FROM golang:1.10-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /XPSchain
RUN cd /XPSchain && make bootnode

RUN chmod +x /XPSchain/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="genisyskernel@xpayments.org"

WORKDIR /XPSchain

COPY --from=builder /XPSchain/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
