# Build Gpay in a stock Go builder container
FROM golang:1.17-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /gpay
RUN cd /gpay && make gpay-all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

RUN set -x \
    && apk add --update --no-cache \
       ca-certificates \
    && rm -rf /var/cache/apk/*
COPY --from=builder /gpay/build/bin/* /usr/local/bin/

EXPOSE 8545 8546 30303 30303/udp
