// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	xpos "github.com/xpaymentsorg/go-xpayments/consensus/xpos"
	mock "github.com/stretchr/testify/mock"
)

// IGenisysClient is an autogenerated mock type for the IGenisysClient type
type IGenisysClient struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IGenisysClient) Close() {
	_m.Called()
}

// Fetch provides a mock function with given fields: path, query
func (_m *IGenisysClient) Fetch(path string, query string) (*xpos.ResponseWithHeight, error) {
	ret := _m.Called(path, query)

	var r0 *xpos.ResponseWithHeight
	if rf, ok := ret.Get(0).(func(string, string) *xpos.ResponseWithHeight); ok {
		r0 = rf(path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xpos.ResponseWithHeight)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchStateSyncEvents provides a mock function with given fields: fromID, to
func (_m *IGenisysClient) FetchStateSyncEvents(fromID uint64, to int64) ([]*xpos.EventRecordWithTime, error) {
	ret := _m.Called(fromID, to)

	var r0 []*xpos.EventRecordWithTime
	if rf, ok := ret.Get(0).(func(uint64, int64) []*xpos.EventRecordWithTime); ok {
		r0 = rf(fromID, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xpos.EventRecordWithTime)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64, int64) error); ok {
		r1 = rf(fromID, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchWithRetry provides a mock function with given fields: path, query
func (_m *IGenisysClient) FetchWithRetry(path string, query string) (*xpos.ResponseWithHeight, error) {
	ret := _m.Called(path, query)

	var r0 *xpos.ResponseWithHeight
	if rf, ok := ret.Get(0).(func(string, string) *xpos.ResponseWithHeight); ok {
		r0 = rf(path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*xpos.ResponseWithHeight)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
